dist: travis
language: cpp
compiler:
    - gcc
addons:
    apt:
        packages:
            - g++-6
            - libboost-test-dev
            - cmake
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install g++-6 libboost-test-dev cmake
script: cmake . && make && tests/lazytests
notifications:
    email:
        recipients:
            - laparca@laparca.es
        on_success: change
        on_failure: allways
