#dist: trusty

language: cpp
compiler:
    - gcc

addons:
    apt:
        packages:
            - g++-6
            - libboost-test1.55-dev
            - cmake
        sources: &sources
            - ubuntu-toolchain-r-test
            - boost-latest

#before_script:
#    - sudo apt-get update -qq
#    - sudo apt-get install g++-6 libboost-test-dev cmake

install:
    - if [ "$CXX" = "g++" ]; then export CXX=g++-6; fi

script: cmake . && make VERBOSE=S && tests/lazytests

notifications:
    email:
        recipients:
            - laparca@laparca.es
        on_success: change
        on_failure: allways
