language: cpp
compiler:
    - gcc

addons:
    apt:
        packages:
            - g++-6
            - libboost-test1.55-dev
            - cmake
        sources: &sources
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports # for a more recent version of cmake (3.2.3)

install:
    - if [ "$CXX" = "g++" ]; then export CXX=g++-6; fi

script:
    - cmake -DDISABLE_CONCEPTS=ON .
    - make VERBOSE=S
    - tests/lazytests

notifications:
    email:
        recipients:
            - laparca@laparca.es
        on_success: change
        on_failure: allways
